### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by iHedgehog** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#1]
```
[EFI]: Generating serial number, MLB & SmUUID for Clover SMBIOS
chmod: externals/simpleMacSerial/simpleMacSerial.sh: No such file or directory
chmod: externals/simpleMLB/simpleMLB.sh: No such file or directory
./GA-Z77X.sh: line 426: externals/simpleMacSerial/simpleMacSerial.sh: No such file or directory
./GA-Z77X.sh: line 427: externals/simpleMLB/simpleMLB.sh: No such file or directory
simpleMacSerial: generated
simpleMLB: generated
uuidgen: generated D4E6360B-4389-4AAC-844A-848292F3CB91
Set: Entry, ":SMBIOS:SerialNumber", Does Not Exist
Set: Entry, ":RtVariables:MLB", Does Not Exist
Set: Entry, ":SMBIOS:SmUUID", Does Not Exist
[EFI]: Copying patched DSDT to EFI partition
cp: DSDT/compiled/*.aml: No such file or directory
```
During use often can be seen result like "No such file or directory" or "Does Not Exist".
Actually only thing I was able to do with this scripts is got patched DSDT, manually from DSDT Patched.

**Comment by theracermaster** [comment]
Can you post the log files (located in the `logs` directory of the repo)? I think I might have encountered a bug like this, but I thought I had fixed it (perhaps not).

**Comment by iHedgehog** [comment]
@theracermaster https://mega.co.nz/#!HA9j3TAT!_UwKIsY-33yLfRM5Dj18uJj8pM_YrisipJsacPGPH2A

**Comment by theracermaster** [comment]
OK, I pushed some updates to the repo. Run `./GA-Z77X.sh --update` & `./GA-Z77X.sh --cleanup` to get to the latest version.

**Comment by iHedgehog** [comment]
It still doesn't work.
```
[DSDT]: Patching /Users/akim/Desktop/install/Gigabyte-GA-Z77X-DSDT-Patch/DSDT/decompiled/DSDT.dsl...
[DSDT]: Applying general patch for GA-Z77X-UD5H motherboard
patch complete: 133 patches, 216 changes, 0 rejects
patched result written to 'DSDT/decompiled/DSDT.dsl'
[DSDT]: FireWire device located at 06:01.0 in PCIe bus
[DSDT]: Applying FireWire patch to device located at 0x06010000 in DSDT
patchmatic: unable to open patches file 'DSDT/patches/FireWire-.txt'
patch complete: 1 patches, 0 changes, 0 rejects
[DSDT]: Discrete GPU detected, assuming IGPU is for AirPlay Mirroring only
[DSDT]: Injecting ig-platform-id into IGPU device for AirPlay Mirroring
patch complete: 2 patches, 1 changes, 0 rejects
patched result written to 'DSDT/decompiled/DSDT.dsl'
Patching complete. Output written to /Users/akim/Desktop/install/Gigabyte-GA-Z77X-DSDT-Patch/DSDT/patched.
Log available at /Users/akim/Desktop/install/Gigabyte-GA-Z77X-DSDT-Patch/logs/dsdt_patch.log.

[DSDT]: Compiling /Users/akim/Desktop/install/Gigabyte-GA-Z77X-DSDT-Patch/DSDT/patched/DSDT.dsl...
Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 92 Optimizations
mv: rename DSDT/patched/iASL*.aml to DSDT/compiled/DSDT.aml: No such file or directory
Output written to /Users/akim/Desktop/install/Gigabyte-GA-Z77X-DSDT-Patch/DSDT/compiled.
Log available at /Users/akim/Desktop/install/Gigabyte-GA-Z77X-DSDT-Patch/logs/dsdt_compile.log.
```
Logs: https://mega.co.nz/#!WEkjAbIJ!bPn3MfUYJuAfpVIvVXVe7joNzjycnWdnLRBZuNek4T4

**Comment by theracermaster** [comment]
Ugh, I must have missed those. Try the latest version of the script (same commands as earlier), the bug should be fixed now.

**Comment by iHedgehog** [comment]
And we are going further. After Clover installation I have empty `config.plist`
```
➜  Gigabyte-GA-Z77X-DSDT-Patch git:(master) ./GA-Z77X.sh --install-clover
Downloading Clover:
######################################################################## 100.0%
EFI partition (disk0s1) is already mounted at /Volumes/EFI.
[EFI]: Installing Clover to the EFI partition
[EFI]: Installing Clover UEFI Drivers
Downloading HFSPlus.efi:
######################################################################## 100.0%
mv: rename /Users/akim/Desktop/install/Gigabyte-GA-Z77X-DSDT-Patch/config.plist to /Volumes/EFI/EFI/CLOVER/config.plist: No such file or directory
[EFI]: Installing kexts to EFI partition
Downloading RehabMan-FakeSMC:
######################################################################## 100.0%
replace FakeSMC_ACPISensors.kext/Contents/Info.plist? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
./GA-Z77X.sh: line 446: logs/clover_install.log: No such file or directory
[EFI]: tee: logs/clover_install.log: No such file or directory
Detected Intel 82579V GBe.
Downloading IntelMausiEthernet.kext
######################################################################## 100.0%
[EFI]: Generating serial number, MLB & SmUUID for Clover SMBIOS
simpleMacSerial: generated C02LYP20FFYV
simpleMLB: generated Error: Invalid serial number!
uuidgen: generated 85E8C252-3E8A-43A8-9BFE-2F138B7FD7D8
File Doesn't Exist, Will Create: /Volumes/EFI/EFI/CLOVER/config.plist
Set: Entry, ":SMBIOS:SerialNumber", Does Not Exist
Set: Entry, ":RtVariables:MLB", Does Not Exist
Set: Entry, ":SMBIOS:SmUUID", Does Not Exist
[EFI]: Copying patched DSDT to EFI partition
```
##### config.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict/>
</plist>
```
Logs: https://mega.co.nz/#!rFt1nRRD!eSRU_M6kxvtc2c2CYxqaiGwz03HwFmveibSb7_Z0JZg

**Comment by theracermaster** [comment]
HDA injection failed due to the codec device not being present in the IORegistry; we can ignore this for now. Try [this config.plist](https://transfer.sh/15Q2cG/config.plist).

**Comment by iHedgehog** [comment]
I switched off internal audio. I tried it, it works well, but what for? I have working config.plist.

**Comment by theracermaster** [comment]
`-xcpm` is XNU Power Management, it enables more states that the usual AICPUPM mode used by Ivy Bridge (iMac SMBIOSes usually only have the lowest mutliplier, the stock multiplier, and the turbo multipliers).

**Comment by iHedgehog** [comment]
Thank you for `config.plist`, I will use it. But I have changed SMBIOS section to iMac 13,2. Is it ok?
Now HWMonitor shows 3 speed steps (it was 2 before). Is it ok or there must be more states?
Maybe some suggestions or advices? I would appreciate it. =)

**Comment by theracermaster** [comment]
Are you using `-xcpm`? What steps do you get? iMac13,2 is OK, power management is same as iMac13,1.

**Comment by iHedgehog** [comment]
I got your config.plist with `-xcpm` and have just changed SMBIOS section to iMac 13,2.
Actually, according to DPCIManager they are 5: `P States: 16, 25, 30, 35, 37`. Is it ok?

**Comment by theracermaster** [comment]
Yes, that is OK.

**Comment by iHedgehog** [comment]
Well, thanks for your work and help.
